version: '3.9'

volumes:
  api-music-storage:

networks:
  c4_network:
    ipam:
      driver: default
      config:
        - subnet: "172.15.0.0/24"

services:
  gateway:
    image: nginx:1.21-alpine
    restart: always
    container_name: gateway
    networks:
      c4_network:
        ipv4_address: 172.15.0.2
    ports:
      - "80:80"
    extra_hosts:
      - "api.music.internal:172.15.0.3"
    volumes:
      - ./:/var/www/api-music
      - ./configs/nginx/conf.d:/etc/nginx/templates/

  api-music:
    build:
      context: ./
      dockerfile: api-music.Dockerfile
    container_name: api-music
    working_dir: /var/www/api-music
    networks:
      c4_network:
        ipv4_address: 172.15.0.3
    ports:
      - ":9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "mysql.docker.internal:172.15.0.4"
    volumes:
      - ./:/var/www/api-music
      - api-music-storage:/var/www/api-music/storage:rw
  db:
    image: mysql
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty123
      - MYSQL_DATABASE=music
      - MYSQL_USER=music_user
      - MYSQL_PASSWORD=secret
    networks:
      c4_network:
        ipv4_address: 172.15.0.4
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
