version: '3.9'

networks:
  c4_network:
    ipam:
      driver: default
      config:
        - subnet: "172.15.0.0/24"

services:
  gateway:
    image: nginx:1.23-alpine
    restart: always
    container_name: gateway
    networks:
      c4_network:
        ipv4_address: 172.15.0.2
    ports:
      - "80:80"
    extra_hosts:
      - "api.music.internal:172.15.0.3"
    volumes:
      - ./:/var/www/api-server
      - ./configs/nginx/conf.d:/etc/nginx/templates/

  api-server:
    build:
      context: ./
      dockerfile: api-server.Dockerfile
    container_name: api-server
    working_dir: /var/www/api-server
    networks:
      c4_network:
        ipv4_address: 172.15.0.3
    ports:
      - ":9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/api-server